const actions = {
  ADD_ITEM: "ADD_ITEM",
  ADD_TAB: "ADD_TAB",
  REMOVE_ITEM: "REMOVE_ITEM",
  FETCH_ITEMS: "FETCH_ITEMS",
  REMOVE_TAB: "REMOVE_TAB",
  ACTIVE_TAB: "ACTIVE_TAB",
  FETCH_TABS: "FETCH_TABS",
};

export default actions;
